[colors]

[colors.primary]
background = '#1e1e1e'
foreground = '#a7a7a7'
dim_foreground = '#5e6166'

[colors.normal]
black   = '#2d2d2d'
red     = '#c26f76'
green   = '#82a966'
yellow  = '#bc9172'
blue    = '#6fa3cd'
magenta = '#a87bb6'
cyan    = '#68b1ba'
white   = '#a7a7a7'

[colors.bright]
black   = '#5e6166'
red     = '#d4868c'
green   = '#98bf7c'
yellow  = '#d2a788'
blue    = '#85b9e3'
magenta = '#be91cc'
cyan    = '#7ec7d0'
white   = '#c0c0c0'

[colors.dim]
black   = '#252525'
red     = '#a85a60'
green   = '#6c8d54'
yellow  = '#9f785e'
blue    = '#5a87ab'
magenta = '#8c659a'
cyan    = '#56959e'
white   = '#808080'

[colors.cursor]
text   = '#1e1e1e'
cursor = '#82a966'

[colors.selection]
text       = '#1e1e1e'
background = '#82a966'

[colors.search]
matches = { foreground = '#1e1e1e', background = '#bc9172' }
focused_match = { foreground = '#1e1e1e', background = '#82a966' }

[colors.hints]
start   = { foreground = '#1e1e1e', background = '#bc9172' }
end     = { foreground = '#1e1e1e', background = '#82a966' }

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#a7a7a7'
background = '#2d2d2d'

[colors.vi_mode_cursor]
text   = '#1e1e1e'
cursor = '#a87bb6'
