background = #1e1e1e
foreground = #a7a7a7
cursor-color = #82a966
cursor-text = #1e1e1e

palette = 0=#2d2d2d
palette = 1=#c26f76
palette = 2=#82a966
palette = 3=#bc9172
palette = 4=#6fa3cd
palette = 5=#a87bb6
palette = 6=#68b1ba
palette = 7=#a7a7a7

palette = 8=#5e6166
palette = 9=#d4868c
palette = 10=#98bf7c
palette = 11=#d2a788
palette = 12=#85b9e3
palette = 13=#be91cc
palette = 14=#7ec7d0
palette = 15=#c0c0c0
