foreground              #a7a7a7
background              #1e1e1e
selection_foreground    #1e1e1e
selection_background    #82a966

cursor                  #82a966
cursor_text_color       #1e1e1e

url_color               #6fa3cd

active_border_color     #a87bb6
inactive_border_color   #5e6166
bell_border_color       #c26f76

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #1e1e1e
active_tab_background   #a87bb6
inactive_tab_foreground #a7a7a7
inactive_tab_background #2d2d2d
tab_bar_background      #2d2d2d

mark1_foreground #1e1e1e
mark1_background #6fa3cd
mark2_foreground #1e1e1e
mark2_background #a87bb6
mark3_foreground #1e1e1e
mark3_background #68b1ba

color0  #2d2d2d
color8  #5e6166
color1  #c26f76
color9  #d4868c
color2  #82a966
color10 #98bf7c
color3  #bc9172
color11 #d2a788
color4  #6fa3cd
color12 #85b9e3
color5  #a87bb6
color13 #be91cc
color6  #68b1ba
color14 #7ec7d0
color7  #a7a7a7
color15 #c0c0c0
